# action.yml
name: 'Ansbile Action'
author: 'Thomas Pisula'
description: 'Execute Ansible as Github Action.'
inputs:
  nsbl_requirements:
    description: 'requirements file'
    required: true
    default: 'requirements.yml'
  nsbl_inventory:
    description: 'inventory file'
    required: true
    default: 'inventory'
  nsbl_playbook:
    description: 'playbook file'
    required: true
    default: 'site.yml'
  nsbl_workingdirectory:
    description: 'working directory'
    required: true
    default: '.'    
  nsbl_sshkey:
    description: 'sshkey to use for host connections'
    required: false
outputs:
  nsbl_version: 
    description: 'The version of ansible used.'
  nsbl_requirements: 
    description: 'The requirements file used.'
  nsbl_inventory: 
    description: 'The inventory file used.'
  nsbl_playbook: 
    description: 'The playbook file used.'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.nsbl_requirements }}
    - ${{ inputs.nsbl_inventory }}
    - ${{ inputs.nsbl_playbook }}
    - ${{ inputs.nsbl_workingdirectory }}
    - ${{ inputs.nsbl_sshkey }}