# action.yml
name: 'Ansbile Action'
author: 'Thomas Pisula'
description: 'Execute Ansible as Github Action.'
inputs:
  workingDirectory:
    description: 'If set, changes the working directory prior to execution of ansible commands.'
    required: true
    default: '.'  
  requirementsFile:
    description: 'The requirements file to use.'
    required: true
    default: 'requirements.yml'
  inventoryFile:
    description: 'The inventory file to use.'
    required: true
    default: 'inventory'
  playbookFile:
    description: 'The playbook file to use.'
    required: true
    default: 'site.yml'  
  keyFile:
    description: 'Keyfile to use for host connections.'
    required: false
outputs:
  ansibleVersion: 
    description: 'The version of ansible used.'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.workingDirectory }}
    - ${{ inputs.requirementsFile }}
    - ${{ inputs.inventoryFile }}
    - ${{ inputs.playbookFile }}
    - ${{ inputs.keyFile }}