# action.yml
name: 'Ansbile Action'
author: 'Thomas Pisula'
description: 'Execute Ansible as Github Action.'
inputs:
  requirementsFile:
    description: 'requirements file'
    required: true
    default: 'requirements.yml'
  inventoryFile:
    description: 'inventory file'
    required: true
    default: 'inventory'
  playbookFile:
    description: 'playbook file'
    required: true
    default: 'site.yml'
  workingDirectory:
    description: 'working directory'
    required: true
    default: '.'    
  sshKeyFile:
    description: 'sshkey to use for host connections'
    required: false
outputs:
  ansibleVersion: 
    description: 'The version of ansible used.'
  requirementsFile: 
    description: 'The requirements file used.'
  inventoryFile: 
    description: 'The inventory file used.'
  playbookFile: 
    description: 'The playbook file used.'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.requirementsFile }}
    - ${{ inputs.inventoryFile }}
    - ${{ inputs.playbookFile }}
    - ${{ inputs.workingDirectory }}
    - ${{ inputs.sshKeyFile }}