on: [push]

jobs:
  ansible_job:
    runs-on: ubuntu-latest
    name: A job to test ansbile action.
    steps:
      - name: Ansbile action step
        id: ansible
        uses: labrats-work/action-ansible@main
        with:
          nsbl_workingdirectory: "/tests/basic"
          nsbl_requirements: 'requirements.yml'
          nsbl_inventory: 'inventory'
          nsbl_playbook: 'site.yml'

      - name: Get the output
        run: echo "version ${{ steps.ansible.outputs.ansible_version }}"

      - name: Get the output
        run: echo "inventory file ${{ steps.ansible.outputs.ansible_inventory }}"

      - name: Get the output
        run: echo "requirements file ${{ steps.ansible.outputs.ansible_requirements }}"
